networks:
  ticketz:

volumes:
  postgres_data:
  redis_data:
  backend_public:
  backend_private:

services:

  backend:
    build:
      context: ./backend
    volumes:
      - backend_public:/usr/src/app/public
      - backend_private:/usr/src/app/private
    environment:
      # Configuração local do backend
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=3000
      - BACKEND_PATH=/backend
      - EMAIL_ADDRESS=admin@ticketz.host
      - TZ=America/Sao_Paulo
      - BACKEND_URL=http://localhost:3000/backend
      - FRONTEND_URL=http://localhost:3000
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ticketz
      - DB_NAME=ticketz
      - DB_TIMEZONE=-03:00
      - REDIS_URI=redis://redis:6379
      - REDIS_OPT_LIMITER_MAX=1
      - REDIS_OPT_LIMITER_DURATION=3000
      - USER_LIMIT=10000
      - CONNECTIONS_LIMIT=100000
      - CLOSED_SEND_BY_ME=true
      - VERIFY_TOKEN=ticketz
      - SOCKET_ADMIN=true
      - JWT_SECRET=localsecretkey123456789abcdefghijklmnopqrstuvwxyz
      - JWT_REFRESH_SECRET=localrefreshsecret123456789abcdefghijklmnopqrstuvwxyz
      - ENV_TOKEN=ticketz
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - ${BACKEND_PORT:-8080}:3000
    networks:
      - ticketz

  frontend:
    ports:
      - ${FRONTEND_PORT:-3000}:80
    build:
      context: ./frontend
    environment:
      # Configuração local do frontend
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - REACT_APP_ENV_TOKEN=ticketz
      - REACT_APP_FRONTEND_URL=http://localhost:3000
      - EMAIL_ADDRESS=admin@ticketz.host
      - ENV_TOKEN=ticketz
    volumes:
      - backend_public:/var/www/backend-public
    restart: always
    depends_on:
      - backend
    networks:
      - ticketz

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ticketz}
      - POSTGRES_DB=${POSTGRES_DB:-ticketz}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=${TZ:-America/Sao_Paulo}
    expose:
      - 5432
    restart: always
    networks:
      - ticketz

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    expose:
      - 6379
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - ticketz 